/**
 * BubbleSystem.ts
 *
 * Pure TypeScript module (no React, no Skia) that manages a pool of up to 40
 * sub-surface bubbles for the water ring puzzle game.
 *
 * ## Layer 4 — Bubble System
 *
 * Bubbles are generated by four triggers:
 *   - Button press        → burst of 5–12 bubbles
 *   - Ring collision      → burst of 2–4 bubbles
 *   - Ring landing on peg → burst of 6–10 bubbles
 *   - Ambient             → 1 bubble every 2–4 s
 *
 * Rise physics:
 *   y(t) = initialY - RISE_SPEED × t_seconds
 *   x(t) = initialX + WOBBLE_AMPLITUDE × sin(WOBBLE_FREQUENCY × 2π × t_seconds + wobblePhase)
 *
 * Opacity: 0.7 × (1 - depth_fraction)
 *   where depth_fraction = (initialY - currentY) / (initialY - waterSurfaceY)
 *
 * On pool overflow, the oldest active bubble is removed (FIFO).
 *
 * Requirements: 38.5, 43.4
 */

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Maximum number of concurrently active bubbles. */
export const MAX_BUBBLES = 40;

/** Vertical rise speed in pixels per second. */
export const RISE_SPEED = 40;

/** Horizontal wobble amplitude in pixels. */
export const WOBBLE_AMPLITUDE = 4;

/** Horizontal wobble frequency in Hz. */
export const WOBBLE_FREQUENCY = 1.5;

/** Starting opacity for every new bubble. */
export const INITIAL_OPACITY = 0.7;

// ---------------------------------------------------------------------------
// Bubble interface
// ---------------------------------------------------------------------------

export interface Bubble {
  /** Unique sequential identifier. */
  id: number;
  /** Current x position (pixels). */
  x: number;
  /** Current y position (pixels). */
  y: number;
  /** Spawn x position (pixels). */
  initialX: number;
  /** Spawn y position (pixels). */
  initialY: number;
  /** Bubble radius in pixels (2–8). */
  radius: number;
  /** Opacity in [0, 1]. Starts at INITIAL_OPACITY and fades to 0 at surface. */
  opacity: number;
  /** Random phase offset for horizontal wobble (radians). */
  wobblePhase: number;
  /** Wall-clock timestamp when this bubble was created (milliseconds). */
  spawnTimeMs: number;
  /** Whether the bubble is currently in use. Inactive bubbles are available for re-use. */
  active: boolean;
}

// ---------------------------------------------------------------------------
// Internal state
// ---------------------------------------------------------------------------

/** Monotonically increasing id counter to identify the order bubbles were spawned. */
let _nextId = 0;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * A minimal seeded pseudo-random number generator interface.
 * Callers supply a function `() => number` returning values in [0, 1).
 * This keeps the module deterministic-friendly for tests and replays.
 */
export type Prng = () => number;

/**
 * Returns a random float in [min, max) using the provided PRNG.
 */
function randomBetween(min: number, max: number, prng: Prng): number {
  return min + prng() * (max - min);
}

/**
 * Returns a random integer in [min, max] (inclusive) using the provided PRNG.
 */
function randomIntBetween(min: number, max: number, prng: Prng): number {
  return Math.floor(min + prng() * (max - min + 1));
}

// ---------------------------------------------------------------------------
// Pool management
// ---------------------------------------------------------------------------

/**
 * Creates a fresh pool of MAX_BUBBLES inactive Bubble objects.
 * Re-using a fixed pool avoids GC pressure during gameplay.
 */
export function createBubblePool(): Bubble[] {
  return Array.from({ length: MAX_BUBBLES }, (_, i) => ({
    id: i,
    x: 0,
    y: 0,
    initialX: 0,
    initialY: 0,
    radius: 4,
    opacity: 0,
    wobblePhase: 0,
    spawnTimeMs: 0,
    active: false,
  }));
}

/**
 * Returns the number of currently active bubbles.
 */
export function countActiveBubbles(bubbles: Bubble[]): number {
  return bubbles.filter((b) => b.active).length;
}

/**
 * Finds an available (inactive) slot in the pool.
 * If the pool is at capacity, the oldest active bubble is evicted (FIFO).
 * Returns the slot index to use.
 */
function acquireSlot(bubbles: Bubble[]): number {
  // First try to find an already-inactive slot.
  const freeIndex = bubbles.findIndex((b) => !b.active);
  if (freeIndex !== -1) {
    return freeIndex;
  }

  // Pool is full — evict the oldest active bubble (lowest spawnTimeMs).
  let oldestIndex = 0;
  let oldestTime = bubbles[0].spawnTimeMs;
  for (let i = 1; i < bubbles.length; i++) {
    if (bubbles[i].spawnTimeMs < oldestTime) {
      oldestTime = bubbles[i].spawnTimeMs;
      oldestIndex = i;
    }
  }
  return oldestIndex;
}

/**
 * Activates one bubble slot with the given parameters.
 */
function spawnOneBubble(
  bubbles: Bubble[],
  x: number,
  y: number,
  radius: number,
  nowMs: number,
  prng: Prng,
): void {
  const index = acquireSlot(bubbles);
  const slot = bubbles[index];

  slot.id = _nextId++;
  slot.x = x;
  slot.y = y;
  slot.initialX = x;
  slot.initialY = y;
  slot.radius = radius;
  slot.opacity = INITIAL_OPACITY;
  slot.wobblePhase = randomBetween(0, Math.PI * 2, prng);
  slot.spawnTimeMs = nowMs;
  slot.active = true;
}

/**
 * Spawns `count` bubbles clustered around (x, y) with a small random spread.
 */
function spawnCluster(
  bubbles: Bubble[],
  x: number,
  y: number,
  count: number,
  minRadius: number,
  maxRadius: number,
  nowMs: number,
  prng: Prng,
): void {
  for (let i = 0; i < count; i++) {
    // Small positional jitter so bubbles don't all stack on the same pixel.
    const jitterX = randomBetween(-8, 8, prng);
    const jitterY = randomBetween(-8, 8, prng);
    const radius = randomBetween(minRadius, maxRadius, prng);
    spawnOneBubble(bubbles, x + jitterX, y + jitterY, radius, nowMs, prng);
  }
}

// ---------------------------------------------------------------------------
// Generation triggers
// ---------------------------------------------------------------------------

/**
 * Spawns 5–12 bubbles at (x, y) from a button-press event.
 * Bubble radii lean smaller (2–5 px) for button press bursts.
 *
 * Requirements: 43.4
 */
export function spawnFromButtonPress(
  bubbles: Bubble[],
  x: number,
  y: number,
  nowMs: number,
  prng: Prng,
): void {
  const count = randomIntBetween(5, 12, prng);
  spawnCluster(bubbles, x, y, count, 2, 5, nowMs, prng);
}

/**
 * Spawns 2–4 small bubbles at (x, y) from a ring-collision event.
 *
 * Requirements: 43.4
 */
export function spawnFromRingCollision(
  bubbles: Bubble[],
  x: number,
  y: number,
  nowMs: number,
  prng: Prng,
): void {
  const count = randomIntBetween(2, 4, prng);
  spawnCluster(bubbles, x, y, count, 2, 4, nowMs, prng);
}

/**
 * Spawns 6–10 medium bubbles at (x, y) from a ring landing on a peg.
 *
 * Requirements: 43.4
 */
export function spawnFromRingLanding(
  bubbles: Bubble[],
  x: number,
  y: number,
  nowMs: number,
  prng: Prng,
): void {
  const count = randomIntBetween(6, 10, prng);
  spawnCluster(bubbles, x, y, count, 3, 8, nowMs, prng);
}

/**
 * Spawns a single ambient bubble at a random x position along the water surface.
 *
 * Requirements: 43.4
 */
export function spawnAmbient(
  bubbles: Bubble[],
  waterSurfaceY: number,
  arenaWidth: number,
  nowMs: number,
  prng: Prng,
): void {
  const x = randomBetween(0, arenaWidth, prng);
  // Start a bit below the surface.
  const y = waterSurfaceY + randomBetween(20, 60, prng);
  const radius = randomBetween(2, 4, prng);
  spawnOneBubble(bubbles, x, y, radius, nowMs, prng);
}

// ---------------------------------------------------------------------------
// Physics update
// ---------------------------------------------------------------------------

/**
 * Updates all active bubbles for the current frame.
 *
 * - Moves each bubble upward at RISE_SPEED px/s.
 * - Applies sinusoidal x-wobble.
 * - Fades opacity as bubble approaches the water surface.
 * - Deactivates bubbles that reach or cross waterSurfaceY.
 *
 * Returns the array of bubbles that were deactivated (popped) this frame,
 * so callers can fire micro-ripple events for each popped bubble.
 *
 * Rise formula:   y(t) = initialY - RISE_SPEED × t_seconds
 * Wobble formula: x(t) = initialX + WOBBLE_AMPLITUDE × sin(WOBBLE_FREQUENCY × 2π × t_seconds + wobblePhase)
 * Opacity:        INITIAL_OPACITY × (1 - depthFraction)
 *   where depthFraction = (initialY - currentY) / (initialY - waterSurfaceY)
 *
 * Requirements: 38.5
 *
 * @param bubbles       The bubble pool (mutated in place).
 * @param nowMs         Current wall-clock time in milliseconds.
 * @param waterSurfaceY Y-coordinate of the water surface (smaller y = higher on screen).
 * @returns             Array of bubbles that popped this frame (now inactive).
 */
export function updateBubbles(
  bubbles: Bubble[],
  nowMs: number,
  waterSurfaceY: number,
): Bubble[] {
  const popped: Bubble[] = [];

  for (const bubble of bubbles) {
    if (!bubble.active) {
      continue;
    }

    const tSeconds = (nowMs - bubble.spawnTimeMs) / 1000;

    // Update y position (rise upward).
    bubble.y = bubble.initialY - RISE_SPEED * tSeconds;

    // Update x position (wobble).
    bubble.x =
      bubble.initialX +
      WOBBLE_AMPLITUDE * Math.sin(WOBBLE_FREQUENCY * 2 * Math.PI * tSeconds + bubble.wobblePhase);

    // Calculate how far the bubble has risen as a fraction of total travel.
    const totalTravel = bubble.initialY - waterSurfaceY;
    const depthFraction =
      totalTravel > 0 ? (bubble.initialY - bubble.y) / totalTravel : 1;

    // Clamp depth fraction to [0, 1] to handle edge cases.
    const clampedFraction = Math.min(1, Math.max(0, depthFraction));
    bubble.opacity = INITIAL_OPACITY * (1 - clampedFraction);

    // Deactivate if reached or crossed the water surface.
    if (bubble.y <= waterSurfaceY) {
      bubble.y = waterSurfaceY; // snap to surface
      bubble.opacity = 0;
      bubble.active = false;
      popped.push(bubble);
    }
  }

  return popped;
}
